/* ============================================================
   GRADE-LEVEL LESSONS — Grades 3, 4 and 5
   Aligned to what Anne Arundel County Public Schools (Maryland)
   teaches: the Maryland College and Career-Ready Standards for
   math and English language arts (the same standards MCAP tests)
   and the Next Generation Science Standards Maryland adopted.
   Each lesson = a short teach (3 cards) + practice questions.
   The correct answer is always opts[0]; the app shuffles choices.
   ============================================================ */
"use strict";
const GRADE_NAMES={3:"3rd Grade",4:"4th Grade",5:"5th Grade"};
const LESSONS={
/* ───────────────────────── GRADE 3 ───────────────────────── */
3:[
{id:"m3-1",subject:"math",lvl:2,title:"Equal Groups: Multiplication",std:"3.OA.A.1",stdName:"Understand multiplication as equal groups",
 intro:"Multiplication is a fast way to add the same number again and again. Coach loves it because teams come in equal groups!",
 teach:[{i:"👥",t:"Picture equal groups. 3 hoops with 4 balls at each hoop is 3 groups of 4."},{i:"➕",t:"You could add: 4 + 4 + 4 = 12. Multiplication says the same thing faster: 3 × 4 = 12."},{i:"🎯",t:"The first number is how many groups. The second is how many in each group."}],
 qs:[
 {q:"Coach sets up 4 hoops with 5 balls at each hoop. Which multiplication shows the total balls?",opts:["4 × 5 = 20","4 + 5 = 9","5 − 4 = 1","4 × 4 = 16"],a:0,topic:"multiplication",teach:[{i:"👥",t:"4 hoops means 4 groups. 5 balls in each group."},{i:"✖️",t:"Groups × in-each-group: 4 × 5."},{i:"🎯",t:"4 × 5 = 20 balls."}]},
 {q:"Which addition means the same as 3 × 6?",opts:["6 + 6 + 6","3 + 6","3 + 3 + 3 + 3 + 3 + 3 + 6","6 + 3 + 6"],a:0,topic:"multiplication",teach:[{i:"🔁",t:"3 × 6 means 3 groups of 6."},{i:"➕",t:"Three sixes: 6 + 6 + 6."},{i:"🎯",t:"Both equal 18."}]},
 {q:"Prince scores 2 points on each of 7 layups. How many points is that?",opts:["14","9","5","27"],a:0,topic:"multiplication",teach:[{i:"🏀",t:"7 layups, 2 points each: 7 groups of 2."},{i:"✖️",t:"7 × 2 = 14."},{i:"🎯",t:"14 points from layups."}]},
 {q:"There are 6 rows of chairs with 8 chairs in each row. How many chairs?",opts:["48","14","42","68"],a:0,topic:"multiplication",teach:[{i:"🪑",t:"6 rows = 6 groups. 8 chairs in each."},{i:"✖️",t:"6 × 8 = 48."},{i:"🎯",t:"48 chairs in all."}]}
]},
{id:"m3-2",subject:"math",lvl:2,title:"Fair Shares: Division",std:"3.OA.A.2",stdName:"Understand division as sharing equally",
 intro:"Division is sharing fairly. When 12 basketballs go to 3 hoops equally, division tells you how many each hoop gets.",
 teach:[{i:"🏀",t:"Start with the total. 12 balls must be shared by 3 hoops."},{i:"➗",t:"Deal them out one at a time until they are gone. Each hoop ends with 4. That is 12 ÷ 3 = 4."},{i:"🔁",t:"Division undoes multiplication. Since 3 × 4 = 12, you know 12 ÷ 3 = 4."}],
 qs:[
 {q:"Coach shares 18 jerseys equally among 6 players. How many jerseys does each player get?",opts:["3","12","24","4"],a:0,topic:"division",teach:[{i:"👕",t:"18 jerseys into 6 equal groups."},{i:"➗",t:"18 ÷ 6 = 3."},{i:"🎯",t:"Each player gets 3."}]},
 {q:"Which multiplication fact helps you solve 20 ÷ 4?",opts:["4 × 5 = 20","20 × 4 = 80","4 + 5 = 9","20 − 4 = 16"],a:0,topic:"division",teach:[{i:"🔁",t:"Division and multiplication are partners."},{i:"❓",t:"Ask: 4 times WHAT equals 20?"},{i:"🎯",t:"4 × 5 = 20, so 20 ÷ 4 = 5."}]},
 {q:"24 fans sit in 4 equal rows. How many fans in each row?",opts:["6","20","8","28"],a:0,topic:"division",teach:[{i:"🪑",t:"24 fans shared into 4 rows."},{i:"➗",t:"24 ÷ 4 = 6."},{i:"🎯",t:"6 fans per row."}]},
 {q:"Ama has 15 stickers. She puts 5 on each page. How many pages does she fill?",opts:["3","10","20","5"],a:0,topic:"division",teach:[{i:"📒",t:"This asks how many groups of 5 fit in 15."},{i:"➗",t:"15 ÷ 5 = 3."},{i:"🎯",t:"3 pages."}]}
]},
{id:"m3-3",subject:"math",lvl:3,title:"Fractions of a Whole",std:"3.NF.A.1",stdName:"Understand a fraction as equal parts of a whole",
 intro:"A fraction names part of a whole that is cut into EQUAL pieces. The bottom number counts the pieces; the top counts how many you have.",
 teach:[{i:"🍕",t:"Cut a pizza into 4 equal slices. Each slice is 1/4 — one fourth."},{i:"🔢",t:"Bottom number (denominator) = how many equal parts in the whole. Top number (numerator) = how many parts you are talking about."},{i:"🎯",t:"Eat 3 of those 4 slices and you ate 3/4 of the pizza."}],
 qs:[
 {q:"A court is divided into 8 equal zones. Prince guards 3 of them. What fraction of the court does he guard?",opts:["3/8","8/3","3/5","1/3"],a:0,topic:"fractions",teach:[{i:"🔢",t:"8 equal zones go on the bottom."},{i:"👆",t:"He guards 3 of them, so 3 goes on top."},{i:"🎯",t:"3/8 of the court."}]},
 {q:"Which picture shows halves?",opts:["A circle cut into 2 equal pieces","A circle cut into 2 pieces, one big and one tiny","A circle cut into 4 equal pieces","A whole circle with no cuts"],a:0,topic:"fractions",teach:[{i:"⚖️",t:"Halves must be 2 EQUAL pieces."},{i:"❌",t:"Unequal pieces are not halves, even if there are two of them."},{i:"🎯",t:"2 equal pieces = halves."}]},
 {q:"In the fraction 5/6, what does the 6 tell you?",opts:["The whole is cut into 6 equal parts","You have 6 parts","There are 6 wholes","Nothing"],a:0,topic:"fractions",teach:[{i:"🔢",t:"The bottom number is the denominator."},{i:"✂️",t:"It tells how many equal parts make one whole."},{i:"🎯",t:"6 equal parts in the whole."}]},
 {q:"A water bottle is split into 3 equal parts. Kofi drinks 1 part. How much did he drink?",opts:["1/3","1/2","3/1","1/4"],a:0,topic:"fractions",teach:[{i:"🧴",t:"3 equal parts — thirds."},{i:"👆",t:"He drank 1 of the 3."},{i:"🎯",t:"1/3 of the bottle."}]}
]},
{id:"e3-1",subject:"english",lvl:2,title:"Main Idea and Key Details",std:"RI.3.2",stdName:"Determine the main idea and the key details that support it",
 intro:"The main idea is what a paragraph is MOSTLY about. Key details are the smaller facts that prove it.",
 teach:[{i:"☂️",t:"Think of the main idea as an umbrella. Every detail fits underneath it."},{i:"🔍",t:"Ask: what do all the sentences have in common? That shared topic is the main idea."},{i:"🎯",t:"Details answer who, what, where, when and how. They hold the main idea up."}],
 qs:[
 {q:"'Lions live in groups called prides. A pride shares food. The lionesses hunt together. Cubs play together.' What is the main idea?",opts:["Lions live and work together in prides","Cubs like to play","Lionesses are good hunters","Lions eat food"],a:0,topic:"main idea",teach:[{i:"☂️",t:"Every sentence is about lions doing things together."},{i:"🔍",t:"Sharing, hunting together, playing together — all under one umbrella."},{i:"🎯",t:"Main idea: lions live and work together in prides."}]},
 {q:"Which sentence is a KEY DETAIL, not the main idea? 'Basketball keeps you healthy. Running builds strong legs. Jumping makes your heart pump. Passing sharpens your eyes.'",opts:["Running builds strong legs","Basketball keeps you healthy","Sports are fun","Basketball is hard"],a:0,topic:"main idea",teach:[{i:"☂️",t:"'Basketball keeps you healthy' is the umbrella."},{i:"🔍",t:"Strong legs, heart pumping, sharp eyes are examples that prove it."},{i:"🎯",t:"'Running builds strong legs' is a detail."}]},
 {q:"A good title for a paragraph about how kente is woven, dyed and worn at festivals would be...",opts:["All About Kente Cloth","How to Play Basketball","Festival Foods","The Color Red"],a:0,topic:"main idea",teach:[{i:"🧵",t:"Weaving, dyeing, wearing — all about kente."},{i:"🏷️",t:"A title should match the main idea."},{i:"🎯",t:"'All About Kente Cloth' fits."}]},
 {q:"To find the main idea of a paragraph, the best question to ask is...",opts:["What is this mostly about?","What is the last word?","How many sentences are there?","Who is the author?"],a:0,topic:"main idea",teach:[{i:"❓",t:"Main idea = what it is MOSTLY about."},{i:"❌",t:"Counting sentences or finding the last word does not tell you the topic."},{i:"🎯",t:"Ask 'What is this mostly about?'"}]}
]},
{id:"e3-2",subject:"english",lvl:2,title:"Prefixes and Suffixes",std:"L.3.4.b",stdName:"Use known affixes to figure out the meaning of a word",
 intro:"Word parts are clues. A prefix goes on the front of a word and a suffix goes on the end. Each one changes the meaning in a predictable way.",
 teach:[{i:"⬅️",t:"Prefixes: un- means not (unhappy), re- means again (replay), pre- means before (pregame)."},{i:"➡️",t:"Suffixes: -ful means full of (hopeful), -less means without (fearless), -er means a person who (player)."},{i:"🎯",t:"Chop the word: prefix + root + suffix. Then put the meanings together."}],
 qs:[
 {q:"What does 'unbeaten' mean?",opts:["Not beaten","Beaten again","Beaten before","Full of beats"],a:0,topic:"word parts",teach:[{i:"⬅️",t:"un- means NOT."},{i:"🔗",t:"un + beaten = not beaten."},{i:"🎯",t:"An unbeaten team has not lost."}]},
 {q:"Which word means 'without care'?",opts:["careless","careful","recare","precare"],a:0,topic:"word parts",teach:[{i:"➡️",t:"-less means without."},{i:"🔗",t:"care + less = without care."},{i:"🎯",t:"Careless."}]},
 {q:"'Preheat the oven' means heat it...",opts:["Before","After","Again","Never"],a:0,topic:"word parts",teach:[{i:"⬅️",t:"pre- means before."},{i:"🍞",t:"You preheat BEFORE the food goes in."},{i:"🎯",t:"Heat it before."}]},
 {q:"A 'teacher' is a person who teaches. What does the suffix -er mean here?",opts:["A person who does something","Not","Again","Very small"],a:0,topic:"word parts",teach:[{i:"➡️",t:"-er turns an action into a person who does it."},{i:"🏀",t:"play → player, teach → teacher."},{i:"🎯",t:"A person who does something."}]}
]},
{id:"e3-3",subject:"english",lvl:3,title:"Character Traits from Actions",std:"RL.3.3",stdName:"Describe characters and explain how their actions drive the story",
 intro:"Authors rarely say 'she was brave.' They SHOW it. Watch what a character does and says, then name the trait.",
 teach:[{i:"👀",t:"Actions are clues. A character who shares her lunch is generous. One who keeps trying is determined."},{i:"💬",t:"Words are clues too. 'I'll go first!' sounds brave or eager."},{i:"🎯",t:"Trait words: brave, kind, honest, stubborn, curious, patient, selfish, loyal."}],
 qs:[
 {q:"Kwame found a wallet on the bus and walked ten blocks to return it. Which trait fits Kwame?",opts:["Honest","Lazy","Rude","Shy"],a:0,topic:"character traits",teach:[{i:"👀",t:"He returned money that was not his, even though it took effort."},{i:"💡",t:"Returning what belongs to others shows honesty."},{i:"🎯",t:"Honest."}]},
 {q:"'Esi asked the new girl to sit with her at lunch and introduced her to everyone.' Esi is...",opts:["Kind and welcoming","Bossy","Nervous","Greedy"],a:0,topic:"character traits",teach:[{i:"👀",t:"Inviting someone new and helping them meet people."},{i:"💡",t:"That is kindness in action."},{i:"🎯",t:"Kind and welcoming."}]},
 {q:"Which action shows a character is PATIENT?",opts:["Waiting calmly while his little brother ties his shoes","Yelling 'hurry up!'","Grabbing the ball from a teammate","Leaving the line early"],a:0,topic:"character traits",teach:[{i:"⏳",t:"Patient means able to wait without getting upset."},{i:"❌",t:"Yelling, grabbing and leaving are the opposite."},{i:"🎯",t:"Waiting calmly shows patience."}]},
 {q:"Yaw kept shooting free throws after everyone left, night after night. His actions show he is...",opts:["Determined","Forgetful","Careless","Sleepy"],a:0,topic:"character traits",teach:[{i:"👀",t:"He keeps working even when nobody is watching."},{i:"💡",t:"Sticking with a goal is determination."},{i:"🎯",t:"Determined."}]}
]},
{id:"c3-1",subject:"comprehension",lvl:2,title:"The Missing Sneaker",std:"RL.3.1",stdName:"Ask and answer questions using the text as evidence",
 story:{title:"The Missing Sneaker",text:"It was the morning of the big game, and Kofi could only find one sneaker. He looked under his bed. He looked in the closet. He even looked in the refrigerator, just in case. His little sister Abena giggled from the doorway. Kofi followed the giggle to the back porch. There sat the sneaker, filled with dirt and a tiny sunflower seed. \"I planted a sneaker garden,\" Abena said proudly. Kofi wanted to be angry, but he laughed instead. He dumped out the dirt, gave Abena a flowerpot, and made it to the game with two minutes to spare."},
 qs:[
 {q:"What problem does Kofi have at the start of the story?",opts:["He can only find one sneaker","He is late for school","His sister is missing","He lost the game"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Look at the first sentence."},{i:"📖",t:"'Kofi could only find one sneaker.'"},{i:"🎯",t:"His sneaker is missing."}]},
 {q:"Where was the sneaker?",opts:["On the back porch","Under his bed","In the refrigerator","In the closet"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Kofi followed the giggle."},{i:"📖",t:"'Kofi followed the giggle to the back porch. There sat the sneaker...'"},{i:"🎯",t:"On the back porch."}]},
 {q:"Why did Abena put dirt in the sneaker?",opts:["She was planting a sneaker garden","She wanted to hide it","She was cleaning it","She was angry at Kofi"],a:0,topic:"comprehension",teach:[{i:"💬",t:"Abena tells us herself."},{i:"📖",t:"'I planted a sneaker garden,' Abena said proudly."},{i:"🎯",t:"She was making a garden."}]},
 {q:"How does Kofi react when he finds the sneaker?",opts:["He laughs and gives Abena a flowerpot","He yells at Abena","He cries","He skips the game"],a:0,topic:"inference",teach:[{i:"🔍",t:"Find the sentence after Abena speaks."},{i:"📖",t:"'Kofi wanted to be angry, but he laughed instead... gave Abena a flowerpot.'"},{i:"🎯",t:"He laughs and gives her a flowerpot."}]},
 {q:"Which word BEST describes Kofi at the end of the story?",opts:["Understanding","Mean","Frightened","Lazy"],a:0,topic:"inference",teach:[{i:"💡",t:"He could have been angry but chose to laugh and help."},{i:"👀",t:"Choosing kindness over anger shows understanding."},{i:"🎯",t:"Understanding."}]}
]},
{id:"c3-2",subject:"comprehension",lvl:3,title:"Kente for Grandma",std:"RL.3.2",stdName:"Recount a story and determine its central message or lesson",
 story:{title:"Kente for Grandma",text:"Ama wanted to give her grandmother a real kente scarf for her birthday, but the scarf at the market cost more than Ama had saved. Instead of giving up, Ama asked the weaver if she could help. Every day after school she sorted threads by color: gold, green, red and black. The weaver showed her how each color carried a meaning — gold for wealth, green for growth. After three weeks, the weaver handed Ama a small scarf. \"You earned this,\" she said. On her birthday, Grandma held the scarf to her cheek and asked where Ama had bought it. \"I didn't buy it,\" Ama said. \"I helped make it.\" Grandma said it was the finest gift she had ever received."},
 qs:[
 {q:"What was Ama's problem?",opts:["The scarf cost more than she had saved","Grandma did not like kente","The market was closed","She forgot the birthday"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"The problem appears in the first sentence."},{i:"📖",t:"'...the scarf at the market cost more than Ama had saved.'"},{i:"🎯",t:"She could not afford it."}]},
 {q:"How did Ama solve her problem?",opts:["She helped the weaver and earned a scarf","She borrowed money","She stole the scarf","She gave up"],a:0,topic:"story structure",teach:[{i:"🔍",t:"What did she do instead of giving up?"},{i:"📖",t:"'Ama asked the weaver if she could help... The weaver handed Ama a small scarf.'"},{i:"🎯",t:"She worked for it."}]},
 {q:"What does the color gold mean in kente, according to the story?",opts:["Wealth","Growth","Sadness","Speed"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Look for the sentence about colors."},{i:"📖",t:"'gold for wealth, green for growth.'"},{i:"🎯",t:"Gold means wealth."}]},
 {q:"What is the central message of this story?",opts:["Working hard for a gift makes it more meaningful","Kente scarves are expensive","Grandmothers like birthdays","Never go to the market"],a:0,topic:"comprehension",teach:[{i:"💡",t:"A central message is the lesson the whole story teaches."},{i:"📖",t:"Ama worked three weeks; Grandma called it the finest gift ever."},{i:"🎯",t:"Effort makes a gift meaningful."}]},
 {q:"Why did Grandma call it the finest gift she had ever received?",opts:["Because Ama helped make it herself","Because it was the biggest scarf","Because it was from the market","Because it was gold"],a:0,topic:"inference",teach:[{i:"🔍",t:"What did Ama say right before Grandma's words?"},{i:"📖",t:"'I didn't buy it. I helped make it.'"},{i:"🎯",t:"The effort made it special."}]}
]},
{id:"s3-1",subject:"science",lvl:2,title:"Weather and Climate",std:"3-ESS2-1, 3-ESS2-2",stdName:"Describe typical weather conditions and climates in different regions",
 intro:"Weather is what the sky is doing TODAY. Climate is the usual weather a place has year after year. Maryland and Ghana have very different climates!",
 teach:[{i:"🌦️",t:"Weather changes daily: temperature, wind, rain, clouds. Scientists record it with thermometers and rain gauges."},{i:"📅",t:"Climate is the pattern over many years. Maryland has four seasons with cold winters. Ghana near the equator stays warm all year."},{i:"🎯",t:"Weather = today. Climate = usual. Both are measured with data, not guesses."}],
 qs:[
 {q:"'It is 40 degrees and raining in Annapolis this morning.' This describes...",opts:["Weather","Climate","A season","Gravity"],a:0,topic:"weather",teach:[{i:"🌦️",t:"This is what is happening this morning."},{i:"📅",t:"Weather is short-term."},{i:"🎯",t:"It describes weather."}]},
 {q:"Which tool measures how much rain fell?",opts:["Rain gauge","Thermometer","Ruler for shadows","Compass"],a:0,topic:"weather",teach:[{i:"🌧️",t:"A rain gauge collects rain in a tube with marks."},{i:"🌡️",t:"A thermometer measures temperature, not rain."},{i:"🎯",t:"Rain gauge."}]},
 {q:"Ghana is warm all year and Maryland has cold winters. This difference is about...",opts:["Climate","One day's weather","Wind speed today","Clouds"],a:0,topic:"weather",teach:[{i:"📅",t:"'All year' and 'winters' talk about patterns over time."},{i:"🌍",t:"Patterns over years = climate."},{i:"🎯",t:"Climate."}]},
 {q:"Which season in Maryland usually has the HIGHEST temperatures?",opts:["Summer","Winter","Fall","Spring"],a:0,topic:"weather",teach:[{i:"☀️",t:"Summer days are long and the Sun is high."},{i:"❄️",t:"Winter is the coldest."},{i:"🎯",t:"Summer."}]}
]},
{id:"s3-2",subject:"science",lvl:2,title:"Life Cycles",std:"3-LS1-1",stdName:"Organisms have unique and diverse life cycles with birth, growth, reproduction and death",
 intro:"Every living thing has a life cycle: it is born, grows, reproduces and dies. Some, like butterflies, change shape completely along the way.",
 teach:[{i:"🥚",t:"A butterfly's cycle: egg → caterpillar (larva) → chrysalis (pupa) → adult butterfly. The adult lays eggs and the cycle repeats."},{i:"🦁",t:"A lion's cycle is simpler: cub → young lion → adult. Cubs look like small adults."},{i:"🎯",t:"All life cycles share birth, growth, reproduction and death — but the stages can look very different."}],
 qs:[
 {q:"Which is the correct order of a butterfly's life cycle?",opts:["Egg, caterpillar, chrysalis, butterfly","Butterfly, egg, chrysalis, caterpillar","Caterpillar, egg, butterfly, chrysalis","Chrysalis, butterfly, caterpillar, egg"],a:0,topic:"life cycles",teach:[{i:"🥚",t:"It starts as an egg."},{i:"🐛",t:"Egg hatches into a caterpillar, which forms a chrysalis."},{i:"🎯",t:"The adult butterfly comes out last."}]},
 {q:"What do ALL life cycles have in common?",opts:["Birth, growth, reproduction and death","A chrysalis stage","Wings","Living in water"],a:0,topic:"life cycles",teach:[{i:"🔁",t:"Every organism is born, grows, makes new organisms and dies."},{i:"❌",t:"Only some animals have wings or a chrysalis."},{i:"🎯",t:"Birth, growth, reproduction, death."}]},
 {q:"A frog starts as an egg, becomes a tadpole with a tail, then grows legs. This big change in body shape is called...",opts:["Metamorphosis","Hibernation","Migration","Evaporation"],a:0,topic:"life cycles",teach:[{i:"🐸",t:"Tadpole to frog is a total body change."},{i:"📚",t:"Metamorphosis means change of form."},{i:"🎯",t:"Metamorphosis."}]},
 {q:"A seed sprouts, grows into a plant, makes flowers and then new seeds. What stage comes AFTER the flower?",opts:["New seeds","Sprout","Roots","Egg"],a:0,topic:"life cycles",teach:[{i:"🌱",t:"Seed → sprout → plant → flower → seeds."},{i:"🌸",t:"Flowers make the seeds for the next cycle."},{i:"🎯",t:"New seeds."}]}
]},
{id:"s3-3",subject:"science",lvl:3,title:"Forces: Pushes and Pulls",std:"3-PS2-1",stdName:"Balanced and unbalanced forces change an object's motion",
 intro:"A force is a push or a pull. Forces can start something moving, stop it, speed it up or change its direction.",
 teach:[{i:"🤝",t:"Two players push a ball with equal force from opposite sides. The forces are BALANCED and the ball stays still."},{i:"💪",t:"If one pushes harder, the forces are UNBALANCED and the ball moves toward the weaker push."},{i:"🎯",t:"Gravity pulls down. Friction slows sliding things. A bigger force makes a bigger change in motion."}],
 qs:[
 {q:"Two teams pull a rope with the same force. The rope does not move. The forces are...",opts:["Balanced","Unbalanced","Magnetic","Invisible"],a:0,topic:"forces",teach:[{i:"🤝",t:"Same force, opposite directions."},{i:"⚖️",t:"They cancel out, so nothing moves."},{i:"🎯",t:"Balanced."}]},
 {q:"Prince pushes a ball gently and it rolls slowly. He pushes harder and it rolls faster. What does this show?",opts:["A bigger force causes a bigger change in motion","Balls always roll the same speed","Friction makes things faster","Gravity pushes sideways"],a:0,topic:"forces",teach:[{i:"💪",t:"More push = more speed."},{i:"📏",t:"The size of a force changes how much motion changes."},{i:"🎯",t:"Bigger force, bigger change."}]},
 {q:"A rolling ball slows down and stops on the grass. Which force slows it?",opts:["Friction","Magnetism","A push from behind","Sunlight"],a:0,topic:"forces",teach:[{i:"🌾",t:"Grass rubs against the ball."},{i:"🛑",t:"Rubbing that slows motion is friction."},{i:"🎯",t:"Friction."}]},
 {q:"What force pulls a dropped basketball toward the floor?",opts:["Gravity","Friction","Wind","Electricity"],a:0,topic:"forces",teach:[{i:"⬇️",t:"Everything on Earth is pulled toward the ground."},{i:"🌍",t:"That pull is gravity."},{i:"🎯",t:"Gravity."}]}
]}
],
/* ───────────────────────── GRADE 4 ───────────────────────── */
4:[
{id:"m4-1",subject:"math",lvl:3,title:"Multi-Digit Multiplication",std:"4.NBT.B.5",stdName:"Multiply multi-digit numbers using place value and area models",
 intro:"Big multiplication is just small multiplication in pieces. Break the number apart by place value, multiply each piece, then add.",
 teach:[{i:"✂️",t:"To find 23 × 4, break 23 into 20 + 3."},{i:"✖️",t:"Multiply each piece: 20 × 4 = 80 and 3 × 4 = 12."},{i:"🎯",t:"Add the pieces: 80 + 12 = 92. So 23 × 4 = 92."}],
 qs:[
 {q:"Which shows 34 × 5 broken apart by place value?",opts:["(30 × 5) + (4 × 5)","(3 × 5) + (4 × 5)","(30 + 5) × 4","34 + 5"],a:0,topic:"multiplication",teach:[{i:"✂️",t:"34 = 30 + 4."},{i:"✖️",t:"Multiply each part by 5."},{i:"🎯",t:"(30 × 5) + (4 × 5) = 150 + 20 = 170."}]},
 {q:"A team bus holds 46 people. 3 buses go to the tournament. How many people is that?",opts:["138","128","49","146"],a:0,topic:"multiplication",teach:[{i:"✂️",t:"46 = 40 + 6."},{i:"✖️",t:"40 × 3 = 120 and 6 × 3 = 18."},{i:"🎯",t:"120 + 18 = 138 people."}]},
 {q:"12 × 15 = ?",opts:["180","150","120","27"],a:0,topic:"multiplication",teach:[{i:"✂️",t:"Break 15 into 10 + 5."},{i:"✖️",t:"12 × 10 = 120 and 12 × 5 = 60."},{i:"🎯",t:"120 + 60 = 180."}]},
 {q:"Each row of the arena has 28 seats. There are 7 rows in a section. How many seats in a section?",opts:["196","186","35","216"],a:0,topic:"multiplication",teach:[{i:"✂️",t:"28 = 20 + 8."},{i:"✖️",t:"20 × 7 = 140 and 8 × 7 = 56."},{i:"🎯",t:"140 + 56 = 196 seats."}]}
]},
{id:"m4-2",subject:"math",lvl:3,title:"Factors and Multiples",std:"4.OA.B.4",stdName:"Find factor pairs and multiples; identify prime and composite numbers",
 intro:"Factors are the numbers you multiply to make a number. Multiples are what you get when you count by a number. Knowing both makes big math easy.",
 teach:[{i:"🔢",t:"Factor pairs of 12: 1 × 12, 2 × 6, 3 × 4. So the factors of 12 are 1, 2, 3, 4, 6 and 12."},{i:"🔁",t:"Multiples of 4 are 4, 8, 12, 16, 20... just skip-count by 4."},{i:"🎯",t:"A PRIME number has only two factors, 1 and itself (like 7). A COMPOSITE number has more (like 12)."}],
 qs:[
 {q:"Which list shows ALL the factors of 18?",opts:["1, 2, 3, 6, 9, 18","1, 2, 9, 18","2, 3, 6","18, 36, 54"],a:0,topic:"factors and multiples",teach:[{i:"🔢",t:"Find pairs: 1 × 18, 2 × 9, 3 × 6."},{i:"📋",t:"List every number in those pairs."},{i:"🎯",t:"1, 2, 3, 6, 9, 18."}]},
 {q:"Which number is a multiple of 6?",opts:["42","20","27","33"],a:0,topic:"factors and multiples",teach:[{i:"🔁",t:"Skip-count by 6: 6, 12, 18, 24, 30, 36, 42."},{i:"✅",t:"42 is on the list."},{i:"🎯",t:"42."}]},
 {q:"Which number is PRIME?",opts:["13","15","21","9"],a:0,topic:"factors and multiples",teach:[{i:"🔍",t:"A prime has only two factors: 1 and itself."},{i:"❌",t:"15 = 3 × 5, 21 = 3 × 7, 9 = 3 × 3. Those are composite."},{i:"🎯",t:"13 is prime."}]},
 {q:"Coach wants to split 24 players into equal teams. Which team size does NOT work?",opts:["5","4","6","8"],a:0,topic:"factors and multiples",teach:[{i:"🔢",t:"Equal teams means the size must be a factor of 24."},{i:"📋",t:"Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24."},{i:"🎯",t:"5 is not a factor of 24."}]}
]},
{id:"m4-3",subject:"math",lvl:3,title:"Equivalent Fractions and Decimals",std:"4.NF.A.1, 4.NF.C.6",stdName:"Explain fraction equivalence; write fractions with denominators of 10 and 100 as decimals",
 intro:"Different fractions can name the same amount. And fractions out of 10 or 100 can be written as decimals, just like money.",
 teach:[{i:"🍕",t:"1/2 of a pizza is the same amount as 2/4 or 4/8. Multiply top and bottom by the same number and the value stays equal."},{i:"💵",t:"7/10 is written 0.7. 43/100 is written 0.43. Think of cents: 43 cents is 0.43 of a dollar."},{i:"🎯",t:"Equivalent fractions: same size, different cuts. Decimals: fractions written with a point."}],
 qs:[
 {q:"Which fraction is equivalent to 3/4?",opts:["6/8","3/8","4/3","6/4"],a:0,topic:"fractions",teach:[{i:"✖️",t:"Multiply top and bottom of 3/4 by 2."},{i:"🔢",t:"3 × 2 = 6 and 4 × 2 = 8."},{i:"🎯",t:"6/8 equals 3/4."}]},
 {q:"How is 9/10 written as a decimal?",opts:["0.9","9.10","0.09","9.0"],a:0,topic:"decimals",teach:[{i:"🔟",t:"Tenths go one place after the decimal point."},{i:"🔢",t:"9 tenths = 0.9."},{i:"🎯",t:"0.9."}]},
 {q:"Prince made 25 of 100 free throws. As a decimal, that is...",opts:["0.25","2.5","0.025","25.0"],a:0,topic:"decimals",teach:[{i:"💯",t:"25/100 is 25 hundredths."},{i:"💵",t:"Like 25 cents out of a dollar: 0.25."},{i:"🎯",t:"0.25."}]},
 {q:"Which pair shows EQUIVALENT fractions?",opts:["2/3 and 4/6","2/3 and 3/2","1/2 and 1/4","3/5 and 3/10"],a:0,topic:"fractions",teach:[{i:"✖️",t:"2/3 × 2/2 = 4/6."},{i:"❌",t:"Flipping a fraction or changing only one number changes its value."},{i:"🎯",t:"2/3 and 4/6."}]}
]},
{id:"e4-1",subject:"english",lvl:3,title:"Finding the Theme",std:"RL.4.2",stdName:"Determine a theme of a story from details in the text",
 intro:"The theme is the big lesson about life a story teaches. It is bigger than the plot and it is never just one word.",
 teach:[{i:"🎭",t:"Plot is what happens: 'A boy loses a race.' Theme is what it teaches: 'Losing can make you stronger.'"},{i:"🔍",t:"Ask: What did the character learn? How did the character change? That change points to the theme."},{i:"🎯",t:"A theme is a full sentence about life, not a topic word like 'friendship'."}],
 qs:[
 {q:"A story: Ananse hoards all the wisdom in a pot, then drops it and wisdom scatters to everyone. The THEME is...",opts:["Wisdom is meant to be shared, not hoarded","Pots break easily","Ananse climbed a tree","Never carry things"],a:0,topic:"theme",teach:[{i:"🎭",t:"Plot: he tries to keep wisdom; it spreads to all."},{i:"💡",t:"What does that teach about life?"},{i:"🎯",t:"Wisdom should be shared."}]},
 {q:"Which of these is written like a THEME rather than a topic?",opts:["Real friends stand by you when things go wrong","Friendship","Basketball","A boy and his dog"],a:0,topic:"theme",teach:[{i:"📝",t:"A theme is a complete statement about life."},{i:"❌",t:"'Friendship' is only a topic word."},{i:"🎯",t:"'Real friends stand by you...' is a theme."}]},
 {q:"Esi is afraid to sing, practices in secret, then sings at the festival and the crowd cheers. What theme fits?",opts:["Facing your fear can bring joy","Festivals are loud","Singing is easy","Crowds are scary"],a:0,topic:"theme",teach:[{i:"🔍",t:"How did Esi change? Afraid → brave."},{i:"💡",t:"Her courage led to joy."},{i:"🎯",t:"Facing your fear can bring joy."}]},
 {q:"The BEST place to look for a story's theme is...",opts:["How the main character changes or what they learn","The title's first letter","The number of pages","The name of the author"],a:0,topic:"theme",teach:[{i:"🔍",t:"Characters change because of the lesson."},{i:"❌",t:"Page counts and letters do not carry meaning."},{i:"🎯",t:"Watch the character's change."}]}
]},
{id:"e4-2",subject:"english",lvl:3,title:"Inference with Text Evidence",std:"RL.4.1",stdName:"Refer to details and examples when drawing inferences from a text",
 intro:"An inference is a smart guess built from clues in the text plus what you already know. Good readers can always point to the evidence.",
 teach:[{i:"🕵️",t:"Text clue + what you know = inference. 'Kofi's teeth chattered' + you know cold makes teeth chatter = Kofi is cold."},{i:"📌",t:"Evidence is the exact words from the text that support your inference. Quote them!"},{i:"🎯",t:"If you cannot point to a clue in the text, it is a wild guess, not an inference."}],
 qs:[
 {q:"'Ama slammed her locker, stomped down the hall and did not say hi to anyone.' What can you infer?",opts:["Ama is upset about something","Ama is excited for lunch","Ama is sleepy","Ama is late"],a:0,topic:"text evidence",teach:[{i:"🕵️",t:"Slamming, stomping, ignoring friends."},{i:"💡",t:"You know people act that way when upset."},{i:"🎯",t:"Ama is upset."}]},
 {q:"Which sentence is the BEST evidence that a character is nervous?",opts:["'His hands shook as he tied his shoes.'","'He wore a blue jersey.'","'The game started at noon.'","'His name was Yaw.'"],a:0,topic:"text evidence",teach:[{i:"📌",t:"Evidence must connect to the feeling."},{i:"🤲",t:"Shaking hands are a clue for nervousness."},{i:"🎯",t:"'His hands shook...'"}]},
 {q:"'The puppy's water bowl was empty and it kept licking the faucet.' You can infer the puppy is...",opts:["Thirsty","Sleepy","Angry","Full"],a:0,topic:"text evidence",teach:[{i:"🕵️",t:"Empty bowl + licking a faucet."},{i:"💡",t:"Animals seek water when thirsty."},{i:"🎯",t:"Thirsty."}]},
 {q:"An inference is different from a wild guess because an inference...",opts:["Is supported by clues in the text","Is always correct","Uses no evidence","Comes only from your imagination"],a:0,topic:"text evidence",teach:[{i:"📌",t:"Inferences rest on text clues."},{i:"❌",t:"A guess with no clues is just a guess."},{i:"🎯",t:"Supported by clues in the text."}]}
]},
{id:"e4-3",subject:"english",lvl:3,title:"Similes and Metaphors",std:"L.4.5.a",stdName:"Explain the meaning of simple similes and metaphors in context",
 intro:"Writers compare things to paint pictures. A simile uses 'like' or 'as'. A metaphor says one thing IS another.",
 teach:[{i:"🔗",t:"Simile: 'Prince is as quick as lightning.' The words 'as' or 'like' signal the comparison."},{i:"🎭",t:"Metaphor: 'Prince is lightning on the court.' No 'like' or 'as' — it says he IS lightning."},{i:"🎯",t:"Neither is literal. Ask: what two things are compared, and what do they share?"}],
 qs:[
 {q:"'The gym was an oven after practice.' This is a...",opts:["Metaphor meaning the gym was very hot","Simile meaning the gym baked bread","Fact about kitchens","Metaphor meaning the gym was cold"],a:0,topic:"figurative language",teach:[{i:"🎭",t:"It says the gym WAS an oven — no like or as."},{i:"🔥",t:"Ovens are hot, so the gym was hot."},{i:"🎯",t:"Metaphor for very hot."}]},
 {q:"Which sentence contains a SIMILE?",opts:["Kofi runs like a cheetah.","Kofi is a cheetah.","Kofi runs fast.","Kofi saw a cheetah."],a:0,topic:"figurative language",teach:[{i:"🔗",t:"Look for 'like' or 'as'."},{i:"🐆",t:"'Runs like a cheetah' compares with 'like'."},{i:"🎯",t:"Kofi runs like a cheetah."}]},
 {q:"'Her voice was music to the tired team.' What does this mean?",opts:["Her voice was pleasant and comforting","She was singing a song","The team was at a concert","Her voice was loud"],a:0,topic:"figurative language",teach:[{i:"🎭",t:"Voice = music is a metaphor."},{i:"🎵",t:"Music is pleasant; her voice felt that way."},{i:"🎯",t:"Pleasant and comforting."}]},
 {q:"'The defender stuck to Prince like glue.' The comparison tells you the defender...",opts:["Stayed very close to him","Was sticky","Used real glue","Fell down"],a:0,topic:"figurative language",teach:[{i:"🔗",t:"Simile with 'like'."},{i:"🧴",t:"Glue sticks close, so the defender stayed close."},{i:"🎯",t:"Stayed very close."}]}
]},
{id:"c4-1",subject:"comprehension",lvl:3,title:"The Tryout",std:"RL.4.3",stdName:"Describe a character, setting or event in depth using specific details",
 story:{title:"The Tryout",text:"The gym at Glen Burnie Elementary smelled like floor polish and nerves. Forty kids lined the baseline, and only twelve would make the travel team. Prince bounced on his toes and glanced at the bleachers where his father sat with his arms crossed, the way he did when he was worried. When Coach Baker blew the whistle, Prince's first pass sailed out of bounds. His face burned. But he remembered what his grandmother always said: \"Ananse does not win the first time. He wins because he keeps thinking.\" Prince slowed down. He called for the ball, faked left and hit a teammate with a bounce pass for an easy layup. Coach Baker wrote something on his clipboard. When the list went up the next morning, Prince read the twelfth name three times before he believed it was his."},
 qs:[
 {q:"Where does this story take place?",opts:["A school gym in Glen Burnie","A park in Accra","Prince's backyard","A football field"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Setting is in the first sentence."},{i:"📖",t:"'The gym at Glen Burnie Elementary...'"},{i:"🎯",t:"A school gym in Glen Burnie."}]},
 {q:"How do you know Prince's father was worried?",opts:["He sat with his arms crossed, the way he did when worried","He shouted at the coach","He left the gym","He was smiling"],a:0,topic:"text evidence",teach:[{i:"📌",t:"Find the sentence about his father."},{i:"📖",t:"'...his father sat with his arms crossed, the way he did when he was worried.'"},{i:"🎯",t:"Crossed arms was his worried habit."}]},
 {q:"What happened right after Prince's first pass went out of bounds?",opts:["His face burned and he remembered his grandmother's words","He made the team","He quit the tryout","Coach blew the whistle"],a:0,topic:"story structure",teach:[{i:"🎬",t:"Look at the sentences that follow the bad pass."},{i:"📖",t:"'His face burned. But he remembered what his grandmother always said...'"},{i:"🎯",t:"He felt embarrassed, then remembered her words."}]},
 {q:"What does the grandmother's saying about Ananse teach Prince to do?",opts:["Slow down and keep thinking instead of panicking","Give up after one mistake","Pass harder","Run faster"],a:0,topic:"inference",teach:[{i:"💬",t:"'He wins because he keeps thinking.'"},{i:"🔍",t:"Right after, 'Prince slowed down' and made a smart play."},{i:"🎯",t:"Keep thinking, do not panic."}]},
 {q:"Why did Prince read the twelfth name three times?",opts:["He could hardly believe he made the team","He could not read","The list was blurry","He was looking for a friend"],a:0,topic:"inference",teach:[{i:"🔍",t:"'...before he believed it was his.'"},{i:"💡",t:"Reading it again and again shows surprise and joy."},{i:"🎯",t:"He could hardly believe it."}]}
]},
{id:"c4-2",subject:"comprehension",lvl:3,title:"The Talking Drums",std:"RI.4.2",stdName:"Determine the main idea of an informational text and explain how details support it",
 story:{title:"The Talking Drums of Ghana",text:"Long before telephones, people in Ghana sent messages across many miles with drums. The Akan people carved 'talking drums' from wood and stretched animal skin across the top. A skilled drummer could squeeze the drum's cords under one arm to change its pitch, making it rise and fall just like a spoken voice. Because the Akan language uses high and low tones, drummers could copy the tones of real words and sentences. Villages passed a message from one drummer to the next, so news of a festival, a birth or danger could travel faster than any runner. Today, talking drums are still played at ceremonies, and drummers train for years to learn the drum language."},
 qs:[
 {q:"What is the main idea of this text?",opts:["Talking drums let people in Ghana send messages over long distances","Drums are made of wood","Runners are slow","Festivals happen in villages"],a:0,topic:"main idea",teach:[{i:"☂️",t:"Every sentence is about drums sending messages."},{i:"🔍",t:"How they are made, how they copy speech, how villages passed news."},{i:"🎯",t:"Drums sent messages over distance."}]},
 {q:"How did a drummer change the drum's pitch?",opts:["By squeezing the cords under one arm","By hitting it with a rock","By adding water","By singing"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Find the sentence about pitch."},{i:"📖",t:"'...squeeze the drum's cords under one arm to change its pitch...'"},{i:"🎯",t:"Squeezing the cords."}]},
 {q:"Why could the drums copy real words?",opts:["The Akan language uses high and low tones, and the drum can copy them","Drums can speak English","The drummers shouted","The wood was magic"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Look for the word 'because'."},{i:"📖",t:"'Because the Akan language uses high and low tones, drummers could copy the tones...'"},{i:"🎯",t:"The language is tonal like the drum."}]},
 {q:"Which detail supports the idea that drums were FASTER than other ways of sending news?",opts:["News could travel faster than any runner","Drums are carved from wood","Drummers train for years","Skin is stretched across the top"],a:0,topic:"text evidence",teach:[{i:"📌",t:"Evidence must be about speed."},{i:"📖",t:"'...could travel faster than any runner.'"},{i:"🎯",t:"Faster than any runner."}]},
 {q:"The last sentence tells us that talking drums...",opts:["Are still used today at ceremonies","Have been forgotten","Were replaced by phones","Are only in museums"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Read the final sentence."},{i:"📖",t:"'Today, talking drums are still played at ceremonies...'"},{i:"🎯",t:"Still used today."}]}
]},
{id:"s4-1",subject:"science",lvl:3,title:"Energy and Motion",std:"4-PS3-1",stdName:"The faster an object moves, the more energy it has",
 intro:"Energy makes things happen. A moving ball has energy, and the faster it moves the more energy it carries. Energy can also be passed from one object to another.",
 teach:[{i:"🏀",t:"A slow roll barely moves a cup. A fast pass knocks it over. More speed means more energy."},{i:"🔄",t:"When a ball hits a cup, energy transfers from the ball to the cup. That is why the cup moves."},{i:"🎯",t:"Energy is stored, moved and changed, but it does not disappear. Sound and heat are energy too."}],
 qs:[
 {q:"Which ball has the MOST energy of motion?",opts:["A ball thrown fast","A ball rolling slowly","A ball sitting on the floor","A ball in a bag"],a:0,topic:"energy",teach:[{i:"⚡",t:"Faster motion = more energy."},{i:"❌",t:"A still ball has no energy of motion."},{i:"🎯",t:"The fast-thrown ball."}]},
 {q:"A bowling ball knocks the pins over. What happened to the ball's energy?",opts:["It transferred to the pins","It vanished","It turned into water","It stayed only in the ball"],a:0,topic:"energy",teach:[{i:"🔄",t:"Collisions pass energy along."},{i:"🎳",t:"The pins move because they received energy."},{i:"🎯",t:"Transferred to the pins."}]},
 {q:"When you clap your hands hard, you hear a loud sound and your palms feel warm. This shows energy can change into...",opts:["Sound and heat","Only light","Nothing","Water"],a:0,topic:"energy",teach:[{i:"👏",t:"Motion energy became sound you hear."},{i:"🔥",t:"Some became heat you feel."},{i:"🎯",t:"Sound and heat."}]},
 {q:"Two identical carts roll down ramps. Cart A is going faster at the bottom. Which is TRUE?",opts:["Cart A has more energy of motion","Cart B has more energy of motion","They have the same energy","Neither has energy"],a:0,topic:"energy",teach:[{i:"⚡",t:"Same cart, different speed."},{i:"📏",t:"More speed means more energy."},{i:"🎯",t:"Cart A."}]}
]},
{id:"s4-2",subject:"science",lvl:3,title:"Waves and Sound",std:"4-PS4-1",stdName:"Waves have amplitude and wavelength and can cause objects to move",
 intro:"Sound travels as waves. Waves have a height called amplitude and a spacing called wavelength. Bigger and closer waves feel different from small, wide ones.",
 teach:[{i:"🌊",t:"Shake a rope gently: small waves (low amplitude). Shake hard: tall waves (high amplitude). For sound, tall waves mean LOUD."},{i:"📏",t:"Wavelength is the distance from one wave peak to the next. Short wavelengths make high-pitched sounds; long ones make low-pitched sounds."},{i:"🎯",t:"Sound needs something to travel through, like air. Vibrations move the wave, but the air itself only wiggles back and forth."}],
 qs:[
 {q:"A drum hit hard makes a louder sound than a soft tap. What changed about the sound wave?",opts:["The amplitude got bigger","The wave stopped","The wavelength became a circle","The drum got smaller"],a:0,topic:"waves and sound",teach:[{i:"🥁",t:"Louder = taller waves."},{i:"📏",t:"Wave height is amplitude."},{i:"🎯",t:"Bigger amplitude."}]},
 {q:"Which describes wavelength?",opts:["The distance from one wave peak to the next","How tall a wave is","How wet a wave is","The color of a wave"],a:0,topic:"waves and sound",teach:[{i:"📏",t:"Wavelength is a length between repeats."},{i:"🌊",t:"Peak to peak."},{i:"🎯",t:"Distance between peaks."}]},
 {q:"A whistle makes a high-pitched sound. Compared to a low drum, the whistle's waves have...",opts:["A shorter wavelength","A longer wavelength","No wavelength","The same wavelength"],a:0,topic:"waves and sound",teach:[{i:"🎵",t:"High pitch = waves come faster and closer."},{i:"📏",t:"Closer peaks = shorter wavelength."},{i:"🎯",t:"Shorter wavelength."}]},
 {q:"Why can't astronauts hear each other talk in the empty space outside their ship?",opts:["Sound needs air or another material to travel through","Space is too bright","Their voices are too quiet","Helmets block all sound"],a:0,topic:"waves and sound",teach:[{i:"🚀",t:"Sound is a vibration passed through particles."},{i:"❌",t:"Empty space has almost no particles to vibrate."},{i:"🎯",t:"Sound needs a material to travel through."}]}
]},
{id:"s4-3",subject:"science",lvl:3,title:"Weathering and Erosion",std:"4-ESS2-1",stdName:"Water, ice, wind and vegetation break rock apart and move sediment",
 intro:"Earth's surface is always changing. Weathering breaks rock into smaller pieces; erosion carries the pieces away. The Chesapeake Bay shoreline shows both every day.",
 teach:[{i:"🧊",t:"Weathering: water seeps into cracks, freezes and expands, splitting rock. Plant roots pry rocks apart too."},{i:"🌊",t:"Erosion: wind, waves, rivers and ice carry the broken bits (sediment) somewhere else. Bay waves wash sand off beaches."},{i:"🎯",t:"Weathering breaks. Erosion moves. Deposition drops the sediment in a new place."}],
 qs:[
 {q:"Water freezes in a crack in a rock and the rock splits. This is an example of...",opts:["Weathering","Erosion","Deposition","Evaporation"],a:0,topic:"earth changes",teach:[{i:"🧊",t:"The rock is being broken apart."},{i:"📚",t:"Breaking rock = weathering."},{i:"🎯",t:"Weathering."}]},
 {q:"Waves carry sand away from a Chesapeake Bay beach. This is...",opts:["Erosion","Weathering","Freezing","Photosynthesis"],a:0,topic:"earth changes",teach:[{i:"🌊",t:"The sand is being MOVED."},{i:"📚",t:"Moving sediment = erosion."},{i:"🎯",t:"Erosion."}]},
 {q:"Which would SLOW erosion on a hillside?",opts:["Planting grass and trees to hold the soil","Removing all plants","Adding more water","Digging the hill"],a:0,topic:"earth changes",teach:[{i:"🌱",t:"Roots grip soil in place."},{i:"❌",t:"Bare soil washes away easily."},{i:"🎯",t:"Plant grass and trees."}]},
 {q:"A river drops mud and sand at its mouth, building new land. This is called...",opts:["Deposition","Weathering","Melting","Migration"],a:0,topic:"earth changes",teach:[{i:"🏞️",t:"The sediment stops moving and piles up."},{i:"📚",t:"Dropping sediment = deposition."},{i:"🎯",t:"Deposition."}]}
]}
],
/* ───────────────────────── GRADE 5 ───────────────────────── */
5:[
{id:"m5-1",subject:"math",lvl:4,title:"Adding Fractions with Unlike Denominators",std:"5.NF.A.1",stdName:"Add and subtract fractions with unlike denominators using equivalent fractions",
 intro:"You can only add fractions when the pieces are the same size. If the denominators differ, make equivalent fractions first.",
 teach:[{i:"🍕",t:"1/2 + 1/4: halves and fourths are different sizes. Change 1/2 into fourths: 1/2 = 2/4."},{i:"➕",t:"Now add same-size pieces: 2/4 + 1/4 = 3/4."},{i:"🎯",t:"Find a common denominator (a shared multiple), rewrite each fraction, then add the tops only."}],
 qs:[
 {q:"1/3 + 1/6 = ?",opts:["1/2","2/9","2/6","1/9"],a:0,topic:"fractions",teach:[{i:"🔁",t:"1/3 = 2/6."},{i:"➕",t:"2/6 + 1/6 = 3/6."},{i:"🎯",t:"3/6 simplifies to 1/2."}]},
 {q:"Prince ran 1/2 mile, then 1/5 mile more. How far did he run?",opts:["7/10 mile","2/7 mile","1/7 mile","2/10 mile"],a:0,topic:"fractions",teach:[{i:"🔁",t:"Common denominator 10: 1/2 = 5/10 and 1/5 = 2/10."},{i:"➕",t:"5/10 + 2/10 = 7/10."},{i:"🎯",t:"7/10 mile."}]},
 {q:"3/4 − 1/8 = ?",opts:["5/8","2/4","2/8","1/2"],a:0,topic:"fractions",teach:[{i:"🔁",t:"3/4 = 6/8."},{i:"➖",t:"6/8 − 1/8 = 5/8."},{i:"🎯",t:"5/8."}]},
 {q:"Why can't you add 1/3 + 1/4 by simply adding the tops and bottoms to get 2/7?",opts:["Thirds and fourths are different-sized pieces","Because 7 is odd","Because fractions cannot be added","Because 2 is too small"],a:0,topic:"fractions",teach:[{i:"🍕",t:"A third and a fourth are not equal pieces."},{i:"🔁",t:"Rewrite both in twelfths: 4/12 + 3/12 = 7/12."},{i:"🎯",t:"Same-size pieces first."}]}
]},
{id:"m5-2",subject:"math",lvl:4,title:"Decimals: Place Value and Adding",std:"5.NBT.A.3, 5.NBT.B.7",stdName:"Read, write, compare decimals to thousandths; add and subtract decimals",
 intro:"Decimals extend place value to the right of the point: tenths, hundredths, thousandths. Line up the points and adding is just like whole numbers.",
 teach:[{i:"🔢",t:"In 3.475: 3 ones, 4 tenths, 7 hundredths, 5 thousandths."},{i:"⚖️",t:"To compare 0.6 and 0.58, give them the same length: 0.60 vs 0.58. 0.60 is bigger."},{i:"🎯",t:"To add 2.5 + 1.75, line up the decimal points: 2.50 + 1.75 = 4.25."}],
 qs:[
 {q:"In 6.293, which digit is in the HUNDREDTHS place?",opts:["9","2","3","6"],a:0,topic:"decimals",teach:[{i:"🔢",t:"After the point: tenths, hundredths, thousandths."},{i:"👆",t:"2 is tenths, 9 is hundredths, 3 is thousandths."},{i:"🎯",t:"9."}]},
 {q:"Which is greatest?",opts:["0.7","0.65","0.099","0.615"],a:0,topic:"decimals",teach:[{i:"⚖️",t:"Write all to three places: 0.700, 0.650, 0.099, 0.615."},{i:"🔍",t:"Compare tenths first: 7 beats 6 and 0."},{i:"🎯",t:"0.7."}]},
 {q:"A sprint took 12.4 seconds. The next took 11.85 seconds. How much faster was the second sprint?",opts:["0.55 seconds","1.45 seconds","0.45 seconds","1.55 seconds"],a:0,topic:"decimals",teach:[{i:"📏",t:"Line up points: 12.40 − 11.85."},{i:"➖",t:"12.40 − 11.85 = 0.55."},{i:"🎯",t:"0.55 seconds faster."}]},
 {q:"3.6 + 2.75 = ?",opts:["6.35","5.81","6.11","5.35"],a:0,topic:"decimals",teach:[{i:"📏",t:"Write 3.6 as 3.60."},{i:"➕",t:"3.60 + 2.75 = 6.35."},{i:"🎯",t:"6.35."}]}
]},
{id:"m5-3",subject:"math",lvl:4,title:"Volume of Boxes",std:"5.MD.C.5",stdName:"Find the volume of rectangular prisms using length × width × height",
 intro:"Volume is how much space fills a 3-D shape, counted in unit cubes. For a box, multiply length × width × height.",
 teach:[{i:"🧊",t:"Picture a box 4 cubes long, 3 wide, 2 tall. One layer has 4 × 3 = 12 cubes."},{i:"📚",t:"Stack 2 layers: 12 × 2 = 24 cubes. Volume = 24 cubic units."},{i:"🎯",t:"Volume = length × width × height. Units are cubic (like cubic centimeters)."}],
 qs:[
 {q:"A shoebox is 6 inches long, 4 inches wide and 5 inches tall. What is its volume?",opts:["120 cubic inches","15 cubic inches","30 cubic inches","240 cubic inches"],a:0,topic:"volume",teach:[{i:"✖️",t:"6 × 4 = 24 for one layer."},{i:"📚",t:"24 × 5 layers = 120."},{i:"🎯",t:"120 cubic inches."}]},
 {q:"A box has a bottom layer of 10 cubes and is 3 layers tall. Its volume is...",opts:["30 cubic units","13 cubic units","103 cubic units","7 cubic units"],a:0,topic:"volume",teach:[{i:"📚",t:"Each layer has 10 cubes."},{i:"✖️",t:"3 layers: 10 × 3 = 30."},{i:"🎯",t:"30 cubic units."}]},
 {q:"Which unit is used for VOLUME?",opts:["Cubic centimeters","Centimeters","Square centimeters","Degrees"],a:0,topic:"volume",teach:[{i:"📏",t:"Length uses cm, area uses square cm."},{i:"🧊",t:"Volume fills space in three directions: cubic."},{i:"🎯",t:"Cubic centimeters."}]},
 {q:"A cube has edges of 3 cm. Its volume is...",opts:["27 cubic cm","9 cubic cm","6 cubic cm","12 cubic cm"],a:0,topic:"volume",teach:[{i:"🧊",t:"All edges are 3."},{i:"✖️",t:"3 × 3 × 3 = 27."},{i:"🎯",t:"27 cubic cm."}]}
]},
{id:"e5-1",subject:"english",lvl:4,title:"Point of View and the Narrator",std:"RL.5.6",stdName:"Describe how a narrator's point of view influences how events are described",
 intro:"Who is telling the story changes what you learn. A first-person narrator shares their own thoughts. A third-person narrator watches from outside.",
 teach:[{i:"🙋",t:"First person uses I, me, we. You see only what that character sees and feels."},{i:"👀",t:"Third person uses he, she, they. Sometimes the narrator knows everyone's thoughts (omniscient), sometimes only one character's (limited)."},{i:"🎯",t:"Ask: whose eyes am I looking through? What might this narrator NOT know or not tell me?"}],
 qs:[
 {q:"'I gripped the ball and felt my heart pound. Nobody could tell how scared I was.' This is told in...",opts:["First person","Third person limited","Third person omniscient","Second person"],a:0,topic:"point of view",teach:[{i:"🙋",t:"'I' and 'my' are first-person words."},{i:"💭",t:"We get the narrator's private feelings."},{i:"🎯",t:"First person."}]},
 {q:"'Esi thought the test was easy. Across the room, Kojo was sure he had failed.' The narrator knows BOTH characters' thoughts. This is...",opts:["Third person omniscient","First person","Third person limited","A diary"],a:0,topic:"point of view",teach:[{i:"👀",t:"He/she words = third person."},{i:"🧠",t:"Knowing everyone's thoughts = omniscient (all-knowing)."},{i:"🎯",t:"Third person omniscient."}]},
 {q:"A story is told by a player who is angry at the coach. How might this point of view affect the story?",opts:["The coach may be described more harshly than he really is","The story will have no opinions","The coach's thoughts will be shown","Nothing will change"],a:0,topic:"point of view",teach:[{i:"😠",t:"An angry narrator sees through angry eyes."},{i:"⚖️",t:"Readers must remember the narrator may be unfair."},{i:"🎯",t:"The coach may seem harsher."}]},
 {q:"Which sentence is written in THIRD person?",opts:["She laced her shoes and jogged onto the court.","I laced my shoes and jogged onto the court.","We laced our shoes and jogged onto the court.","My shoes were laced and I jogged."],a:0,topic:"point of view",teach:[{i:"👀",t:"Third person uses she, he, they."},{i:"❌",t:"I, we, my are first person."},{i:"🎯",t:"'She laced her shoes...'"}]}
]},
{id:"e5-2",subject:"english",lvl:4,title:"Compare and Contrast Characters",std:"RL.5.3",stdName:"Compare and contrast characters, settings or events using specific details",
 intro:"To compare is to find what is alike. To contrast is to find what is different. Great readers do both using details from the text.",
 teach:[{i:"🟰",t:"Compare: Ananse and Yaa Asantewaa BOTH faced enemies bigger than themselves."},{i:"↔️",t:"Contrast: Ananse won with tricks and wit; Yaa Asantewaa won respect with open courage."},{i:"🎯",t:"Signal words: both, also, similarly (compare); but, however, unlike, whereas (contrast)."}],
 qs:[
 {q:"'Kofi practices alone at dawn. Ama practices with a big group after school. Both make the same number of shots each day.' What is one way Kofi and Ama are ALIKE?",opts:["Both make the same number of shots daily","Both practice at dawn","Both practice in groups","Both skip practice"],a:0,topic:"compare and contrast",teach:[{i:"🟰",t:"Look for 'both'."},{i:"📖",t:"'Both make the same number of shots each day.'"},{i:"🎯",t:"Same number of shots."}]},
 {q:"Using the same passage, how are Kofi and Ama DIFFERENT?",opts:["Kofi practices alone at dawn; Ama practices with a group after school","Kofi does not practice","Ama makes more shots","They play different sports"],a:0,topic:"compare and contrast",teach:[{i:"↔️",t:"Contrast the when and who."},{i:"📖",t:"Alone at dawn vs. group after school."},{i:"🎯",t:"Time and company differ."}]},
 {q:"Which word signals a CONTRAST?",opts:["However","Both","Also","Similarly"],a:0,topic:"compare and contrast",teach:[{i:"↔️",t:"'However' introduces a difference."},{i:"🟰",t:"Both, also, similarly show likeness."},{i:"🎯",t:"However."}]},
 {q:"Two settings: a quiet library and a roaring arena. Which sentence CONTRASTS them correctly?",opts:["Unlike the silent library, the arena thundered with noise","The library and arena are both quiet","The library was louder than the arena","Both places are outside"],a:0,topic:"compare and contrast",teach:[{i:"↔️",t:"'Unlike' signals contrast."},{i:"📖",t:"Silent vs. thundering — a real difference."},{i:"🎯",t:"'Unlike the silent library...'"}]}
]},
{id:"e5-3",subject:"english",lvl:4,title:"Summarizing a Text",std:"RL.5.2",stdName:"Summarize a text, including the theme and how characters respond to challenges",
 intro:"A summary retells the most important parts in your own words, in order, and leaves out small details. Somebody-Wanted-But-So-Then is a great frame.",
 teach:[{i:"🧩",t:"Somebody (who) Wanted (goal) But (problem) So (what they did) Then (how it ended)."},{i:"✂️",t:"Leave out tiny details like what the character ate for breakfast unless it matters to the plot."},{i:"🎯",t:"A good summary is short, in order, in your own words, and includes the main lesson if there is one."}],
 qs:[
 {q:"Which is the BEST summary of 'Kente for Grandma'? (Ama could not afford a scarf, worked for the weaver for three weeks, and gave Grandma the scarf she helped make.)",opts:["Ama wanted a kente scarf for Grandma but could not afford it, so she worked for the weaver and earned one. Grandma loved it.","Ama sorted gold threads on Tuesday.","Grandma had a birthday.","Kente has many colors like gold and green."],a:0,topic:"summarizing",teach:[{i:"🧩",t:"Somebody: Ama. Wanted: scarf. But: too expensive. So: worked. Then: Grandma loved it."},{i:"✂️",t:"Sorting threads on one day is a small detail."},{i:"🎯",t:"The first choice has all the key parts."}]},
 {q:"Which detail should be LEFT OUT of a summary of a story about a boy winning a science fair?",opts:["The color of his socks","His project idea","The problem he had to solve","How the fair ended"],a:0,topic:"summarizing",teach:[{i:"✂️",t:"Summaries keep only what matters to the plot."},{i:"🧦",t:"Sock color does not change the story."},{i:"🎯",t:"Leave out the socks."}]},
 {q:"In the Somebody-Wanted-But-So-Then frame, 'But' stands for...",opts:["The problem the character faces","The ending","The character's name","The setting"],a:0,topic:"summarizing",teach:[{i:"🧩",t:"'But' introduces what gets in the way."},{i:"📖",t:"Somebody wanted X, BUT there was a problem."},{i:"🎯",t:"The problem."}]},
 {q:"A summary should be written...",opts:["In your own words and in the order things happened","By copying the whole story","Out of order","Using only the last sentence"],a:0,topic:"summarizing",teach:[{i:"📝",t:"Own words show understanding."},{i:"🔢",t:"Order keeps it clear."},{i:"🎯",t:"Own words, in order."}]}
]},
{id:"c5-1",subject:"comprehension",lvl:4,title:"The Long Road to Accra",std:"RL.5.2",stdName:"Determine a theme from how characters respond to challenges; summarize the text",
 story:{title:"The Long Road to Accra",text:"When Kwame's family moved from Accra to Maryland, he brought two things: his grandfather's carved chess set and a stubborn silence. At his new school, kids talked fast and joked about things he had never heard of, so he ate lunch alone and played chess against himself. One rainy Friday, a girl named Maya sat down across from him and moved a pawn without asking. He beat her in eleven moves. She came back Monday and lost in twenty. By November she was winning half their games, and a small crowd gathered at their table each day. Kwame still spoke quietly, but now he had a dozen people to speak to. When his grandfather called from Accra and asked how America was, Kwame said, \"It was very far away. Now it is a little closer.\""},
 qs:[
 {q:"What challenge does Kwame face at his new school?",opts:["He feels alone and out of place","He cannot play chess","He is failing math","He lost his chess set"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Look at the second sentence."},{i:"📖",t:"'...kids talked fast and joked about things he had never heard of, so he ate lunch alone...'"},{i:"🎯",t:"He feels alone and out of place."}]},
 {q:"How does Maya change Kwame's situation?",opts:["She keeps coming back to play, and others gather around them","She teaches him English","She moves to Accra","She beats him every day"],a:0,topic:"story structure",teach:[{i:"🎬",t:"Follow the sequence: Friday, Monday, November."},{i:"📖",t:"'She came back Monday... a small crowd gathered at their table each day.'"},{i:"🎯",t:"Her persistence draws others in."}]},
 {q:"What does Kwame mean when he says America is 'a little closer' now?",opts:["He is starting to feel at home","The plane ride got shorter","His school moved","Accra moved"],a:0,topic:"inference",teach:[{i:"🎭",t:"'Far away' and 'closer' are about feelings, not miles."},{i:"💡",t:"Having friends makes a place feel like home."},{i:"🎯",t:"He is starting to feel at home."}]},
 {q:"Which theme BEST fits this story?",opts:["Connection grows when you share what you love and let others in","Chess is the best game","Moving is always easy","Never talk to strangers"],a:0,topic:"theme",teach:[{i:"🔍",t:"How did Kwame change? From silent and alone to surrounded by friends."},{i:"💡",t:"Chess, the thing he loved, became the bridge."},{i:"🎯",t:"Sharing what you love builds connection."}]},
 {q:"Which is the best SUMMARY of the story?",opts:["Kwame, new from Accra, felt alone until a girl started playing chess with him; soon a crowd joined and he began to feel at home.","Kwame owns a chess set.","Maya lost in twenty moves on a Monday.","It rained on Friday."],a:0,topic:"summarizing",teach:[{i:"🧩",t:"Somebody: Kwame. Wanted: to belong. But: alone. So: chess with Maya. Then: felt closer."},{i:"✂️",t:"Rain and move counts are small details."},{i:"🎯",t:"The first choice covers the whole arc."}]}
]},
{id:"c5-2",subject:"comprehension",lvl:4,title:"Why the Bay Matters",std:"RI.5.8",stdName:"Explain how an author uses reasons and evidence to support points",
 story:{title:"Why the Chesapeake Bay Matters",text:"The Chesapeake Bay is the largest estuary in the United States, a place where fresh river water mixes with salty ocean water. This mix makes the Bay a nursery for life: more than 3,600 kinds of plants and animals live there, including blue crabs, oysters and striped bass. The Bay also matters to people. Watermen in Anne Arundel County have caught crabs and oysters for generations, and millions of visitors boat, fish and swim in its waters. But the Bay is fragile. When rain washes fertilizer and dirt from lawns, farms and streets into rivers, it flows to the Bay and feeds algae that use up oxygen, leaving 'dead zones' where fish cannot breathe. Scientists say the fix begins on land: planting trees along streams, keeping soil in place and using less fertilizer. Every yard in Maryland is upstream of the Bay."},
 qs:[
 {q:"What is an estuary?",opts:["A place where fresh water and salt water mix","A deep ocean trench","A type of fish","A frozen lake"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"The first sentence defines it."},{i:"📖",t:"'...a place where fresh river water mixes with salty ocean water.'"},{i:"🎯",t:"Fresh and salt water mixing."}]},
 {q:"Which evidence supports the point that the Bay is a 'nursery for life'?",opts:["More than 3,600 kinds of plants and animals live there","Millions of visitors boat there","Every yard is upstream","Rain washes fertilizer"],a:0,topic:"text evidence",teach:[{i:"📌",t:"Evidence for 'nursery for life' must be about living things."},{i:"📖",t:"'...more than 3,600 kinds of plants and animals live there...'"},{i:"🎯",t:"3,600 kinds of plants and animals."}]},
 {q:"According to the text, what causes 'dead zones'?",opts:["Fertilizer and dirt feed algae that use up oxygen","Too many boats","Cold water","Crabs eating oysters"],a:0,topic:"comprehension",teach:[{i:"🔍",t:"Find the sentence with 'dead zones'."},{i:"📖",t:"'...feeds algae that use up oxygen, leaving dead zones...'"},{i:"🎯",t:"Algae fed by runoff use up oxygen."}]},
 {q:"Why does the author include the watermen of Anne Arundel County?",opts:["To show the Bay matters to people's jobs and traditions","To explain how algae grow","To describe the ocean","To list fish species"],a:0,topic:"text evidence",teach:[{i:"🔍",t:"The sentence follows 'The Bay also matters to people.'"},{i:"💡",t:"Watermen are evidence for that point."},{i:"🎯",t:"It matters to people's livelihoods."}]},
 {q:"What does the last sentence, 'Every yard in Maryland is upstream of the Bay,' mean?",opts:["What people do on their own land affects the Bay","All yards are on hills","Maryland has no rivers","The Bay is in every yard"],a:0,topic:"inference",teach:[{i:"🎭",t:"'Upstream' means water flows from there to the Bay."},{i:"💡",t:"So choices at home reach the Bay."},{i:"🎯",t:"Everyone's land affects the Bay."}]}
]},
{id:"s5-1",subject:"science",lvl:4,title:"Matter: Particles and Mixtures",std:"5-PS1-1, 5-PS1-4",stdName:"Matter is made of particles too small to see; mixing substances can form new ones",
 intro:"Everything is made of tiny particles too small to see. That explains how sugar disappears in water, how smells travel, and how mixing can make something new.",
 teach:[{i:"🔬",t:"Sugar stirred into water seems to vanish, but the sweet taste proves the sugar particles are still there, spread out between water particles."},{i:"👃",t:"You smell popcorn across the room because gas particles from it travel through the air."},{i:"🎯",t:"Some mixtures just mix (salt water). Others make a NEW substance with new properties (baking soda + vinegar fizzes into a gas)."}],
 qs:[
 {q:"Salt dissolves in water and can no longer be seen. What happened to the salt?",opts:["Its particles spread out among the water particles","It disappeared forever","It turned into water","It floated away as air"],a:0,topic:"matter",teach:[{i:"🔬",t:"Matter is made of particles."},{i:"💧",t:"The salt particles mix between the water particles."},{i:"🎯",t:"Spread out, still there."}]},
 {q:"Which observation shows a NEW substance formed?",opts:["Baking soda and vinegar bubble and produce a gas","Sugar dissolves in tea","Ice melts into water","Sand is stirred into water"],a:0,topic:"matter",teach:[{i:"🧪",t:"A new substance has new properties."},{i:"💨",t:"Bubbles of gas that were not there before = something new."},{i:"🎯",t:"Baking soda and vinegar."}]},
 {q:"You can smell fufu cooking from another room. This is evidence that...",opts:["Gas particles travel through the air","Food is very loud","Your nose can see","Air is empty"],a:0,topic:"matter",teach:[{i:"👃",t:"Smell is particles reaching your nose."},{i:"💨",t:"They traveled through the air as a gas."},{i:"🎯",t:"Gas particles move through air."}]},
 {q:"A closed jar of water is weighed, frozen solid and weighed again. The weight is...",opts:["The same, because no particles were added or removed","Heavier","Lighter","Zero"],a:0,topic:"matter",teach:[{i:"⚖️",t:"Freezing changes state, not the amount of matter."},{i:"🔒",t:"Closed jar: nothing in, nothing out."},{i:"🎯",t:"The same."}]}
]},
{id:"s5-2",subject:"science",lvl:4,title:"Ecosystems and Food Webs",std:"5-LS2-1",stdName:"Describe how matter moves among plants, animals, decomposers and the environment",
 intro:"An ecosystem is a community of living things plus their environment. Energy and matter move through it along food chains that connect into a food web.",
 teach:[{i:"☀️",t:"Producers (plants) make food from sunlight. Consumers eat plants or other animals. Decomposers (fungi, bacteria) break down dead things and return nutrients to the soil."},{i:"🔗",t:"In the Chesapeake Bay: algae → tiny shrimp → small fish → striped bass → osprey. Arrows show where the energy goes."},{i:"🎯",t:"Remove one link and the web shifts. Fewer oysters means dirtier water, which affects everything else."}],
 qs:[
 {q:"In a food chain, which organism makes its own food from sunlight?",opts:["A producer, like a plant or algae","A consumer, like a fish","A decomposer, like a mushroom","A predator, like an osprey"],a:0,topic:"ecosystems",teach:[{i:"☀️",t:"Plants and algae use sunlight to make food."},{i:"📚",t:"Food-makers are producers."},{i:"🎯",t:"A producer."}]},
 {q:"What role do decomposers play?",opts:["They break down dead things and return nutrients to the soil","They eat only plants","They make sunlight","They hunt fish"],a:0,topic:"ecosystems",teach:[{i:"🍄",t:"Fungi and bacteria recycle."},{i:"🔄",t:"Nutrients go back to the soil for plants to use."},{i:"🎯",t:"They recycle nutrients."}]},
 {q:"In the chain algae → shrimp → small fish → striped bass, what do the arrows show?",opts:["The direction energy moves as one organism eats another","Which animal is bigger","The order animals were born","Which way the water flows"],a:0,topic:"ecosystems",teach:[{i:"➡️",t:"Arrow points from food to eater."},{i:"⚡",t:"Energy travels along the arrow."},{i:"🎯",t:"Direction of energy."}]},
 {q:"If most of the small fish in a bay disappeared, what would likely happen to the striped bass?",opts:["They would have less food and their numbers might drop","They would grow larger","Nothing would change","They would become plants"],a:0,topic:"ecosystems",teach:[{i:"🔗",t:"Striped bass eat small fish."},{i:"📉",t:"Less food means fewer bass survive."},{i:"🎯",t:"Fewer bass."}]}
]},
{id:"s5-3",subject:"science",lvl:4,title:"Earth's Spheres and Water",std:"5-ESS2-1, 5-ESS2-2",stdName:"Earth's systems interact; describe where Earth's water is found",
 intro:"Earth works as four connected systems: the geosphere (rock and soil), hydrosphere (water), atmosphere (air) and biosphere (living things). Water ties them together.",
 teach:[{i:"🌍",t:"Rain from the atmosphere falls on the geosphere, flows through the hydrosphere and is used by the biosphere. Change one and the others respond."},{i:"💧",t:"Almost all of Earth's water (about 97%) is salty ocean. Most fresh water is frozen in glaciers and ice caps. Only a tiny fraction is in rivers, lakes and groundwater we can drink."},{i:"🎯",t:"That is why protecting rivers, and the Chesapeake Bay they feed, matters so much."}],
 qs:[
 {q:"Which sphere includes all living things?",opts:["Biosphere","Geosphere","Atmosphere","Hydrosphere"],a:0,topic:"earth systems",teach:[{i:"🌱",t:"'Bio' means life."},{i:"📚",t:"Biosphere = living things."},{i:"🎯",t:"Biosphere."}]},
 {q:"Where is MOST of Earth's water found?",opts:["In the salty oceans","In rivers","In lakes","Underground"],a:0,topic:"earth systems",teach:[{i:"🌊",t:"About 97% of Earth's water is ocean."},{i:"💧",t:"Rivers and lakes hold a tiny fraction."},{i:"🎯",t:"The oceans."}]},
 {q:"Where is most of Earth's FRESH water?",opts:["Frozen in glaciers and ice caps","In rivers","In clouds","In swimming pools"],a:0,topic:"earth systems",teach:[{i:"🧊",t:"Most fresh water is locked up as ice."},{i:"💧",t:"Rivers are a small share."},{i:"🎯",t:"Glaciers and ice caps."}]},
 {q:"Heavy rain (atmosphere) washes soil (geosphere) into a river, harming fish (biosphere). This shows that...",opts:["Earth's spheres interact with each other","The spheres never touch","Fish cause rain","Soil is not part of Earth"],a:0,topic:"earth systems",teach:[{i:"🔗",t:"Air, land, water and life all connected in one event."},{i:"🌍",t:"That is how Earth's systems work."},{i:"🎯",t:"The spheres interact."}]}
]}
]
};
/* topic → subject for every lesson topic that is not in the base bank */
const LESSON_TOPIC_SUBJECT={
 "factors and multiples":"math","decimals":"math","volume":"math",
 "main idea":"english","word parts":"english","character traits":"english","theme":"english","text evidence":"english","point of view":"english","compare and contrast":"english","summarizing":"english",
 "weather":"science","life cycles":"science","forces":"science","energy":"science","waves and sound":"science","earth changes":"science","matter":"science","ecosystems":"science","earth systems":"science"
};
function lessonById(id){for(const g in LESSONS){const l=LESSONS[g].find(x=>x.id===id);if(l)return Object.assign({grade:+g},l);}return null;}
function lessonsFor(grade,subject){return (LESSONS[grade]||[]).filter(l=>!subject||l.subject===subject).map(l=>Object.assign({grade:+grade},l));}
